SET(PID_SEARCH_PATHS
  /usr/local
  /opt/local
  ${NINJAPID_PATH}
  )

FIND_PATH(PID_INCLUDE_DIR PidData.hpp
  HINTS
  $ENV{NINJAMOMDIR}
  PATH_SUFFIXES include/ninja/momrecon include
  PATHS ${PID_SEARCH_PATHS}
)

FIND_LIBRARY(PID_LIBRARY_TEMP
  NAMES Pid
  HINTS
  $ENV{NINJAMOMDIR}
  PATH_SUFFIXES lib64/ninja/momrecon lib/ninja/momrecon
  PATHS ${PID_SEARCH_PATHS}
)

IF(PID_LIBRARY_TEMP)
  SET(PID_LIBRARY ${PID_LIBRARY_TEMP} CACHE STRING "Where the PID Library can be found")
  SET(PID_LIBRARY_TEMP "${PID_LIBRARY_TEMP}" CACHE INTERNAL "")
ENDIF(PID_LIBRARY_TEMP)

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(Pid REQUIRED_VARS PID_LIBRARY PID_INCLUDE_DIR)
