SET(CONNECTION_SEARCH_PATHS
  /usr/local
  /opt/local
  ${NINJACONNECTION_PATH}
  )

FIND_PATH(CONNECTION_INCLUDE_DIR ConnectionClass.hpp
  HINTS
  $ENV{NINJAMOMDIR}
  PATH_SUFFIXES include/ninja/momrecon include
  PATHS ${CONNECTION_SEARCH_PATHS}
  )

FIND_LIBRARY(CONNECTION_LIBRARY_TEMP
  NAMES Connection
  HINTS
  $ENV{NINJAMOMDIR}
  PATH_SUFFIXES lib64/ninja/momrecon lib/ninja/momrecon
  PATHS ${CONNECTION_SEARCH_PATHS}
  )

IF(CONNECTION_LIBRARY_TEMP)
  SET(CONNECTION_LIBRARY ${CONNECTION_LIBRARY_TEMP} CACHE STRING "Where the CONNECTION Library can be found")
  SET(CONNECTION_LIBRARY_TEMP "${CONNECTION_LIBRARY_TEMP}" CACHE INTERNAL "")
ENDIF(CONNECTION_LIBRARY_TEMP)

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(Connection REQUIRED_VARS CONNECTION_LIBRARY CONNECTION_INCLUDE_DIR)